server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://ec2-54-87-118-187.compute-1.amazonaws.com:5432/dockapi
    username: dockapi_admin
    password: DockAPI7999
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liIlxN0xZ9vg9htz
            client-secret: 41f0a0bf63e612dbc9e922db7adf2335f17356e7
            scope:
              - repo
              - read:user
              - user:email
              - workflow
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            provider: github
          gitlab:
            client-id: 1f9b84e930927879ccdcb45ba05f114f9d3bfc173322da60dfa2f63585b3f0d7
            client-secret: gloas-6f9f7adedfb3f34f62e4201d4b06092a8877bf71e501b0bb3254846cdaf74642
            scope:
              - read_user
              - read_repository
              - read_api
              - read_registry
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            provider: gitlab
          bitbucket:
            client-id: H59XWbXGYNwF6JUHJr
            client-secret: kuSesaeWKMwt24RUVPAaq7wMAkmFSkcX
            scope:
              - account
              - repository
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            provider: bitbucket

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: username
          bitbucket:
            authorization-uri: https://bitbucket.org/site/oauth2/authorize
            token-uri: https://bitbucket.org/site/oauth2/access_token
            user-info-uri: https://api.bitbucket.org/2.0/user
            user-name-attribute: username

springdoc:
  api-docs:
    path: /api-docs # URL to access the OpenAPI JSON
    enabled: true
  swagger-ui:
    path: /swagger-ui.html # Swagger UI URL
    operationsSorter: method # Sort endpoints by HTTP method
    tagsSorter: alpha # Sort tags alphabetically
    display-request-duration: true # Show how long each request takes
    doc-expansion: none # Collapse all sections by default
    disable-swagger-default-url: true
    persist-authorization: true # Keeps authorization token when refreshing
    enabled: true
    try-it-out-enabled: true
    filter: true
    deep-linking: true
    display-operation-id: true
    syntax-highlight:
      activated: true
      theme: monokai
